pages:
  stage: deploy
  script:
    # public directory to serve as web root
    - mkdir public
    - cp -r core public
    # web-ui files at root of directory
    - cp -r web-ui/* public
    # change js file path according to changed folder structure
    - sed -i -e 's/\.\.\/core\/Instruction\.js/\.\/core\/Instruction\.js/g' ./public/main.js
  artifacts:
    paths:
      - public
  only:
    - main
